<a href="https://colab.research.google.com/github/vmicheni123/Karamoja-Crop-Data-Visualization/blob/main/Karamoja_Food_Security_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Objective**

The objective is to develop visualizations for Kamamoja region in Uganda that is predominantly food insecure. We use python to run the data cleaning

In [ ]:
#Import common python libraries to support in data cleaning
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Open csv document on district crop yield
df = pd.read_csv('/content/Uganda_Karamoja_District_Crop_Yield_Population.csv')
df2 = pd.read_csv('/content/Uganda_Karamoja_Subcounty_Crop_Yield_Population.csv')

In [ ]:
#Look at the dataframe columns and first rows for the first dataset
df.head()

,OBJECTID,DISTRICT_NAME,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,92,ABIM,90385,2771977106,449,1040,5470.068394,3277.295971,1848.621855,1471506,1922567
1,96,AMUDAT,101790,1643582836,205,1297,5765.443719,2973.423860,2733.661014,609552,3545558
2,20,KAABONG,627057,7373606003,279,945,28121.672530,20544.194960,7394.416334,5731830,6987723
3,85,KOTIDO,243157,3641539808,331,1148,53032.649450,50247.443900,1751.372284,16631904,2010575
4,5,MOROTO,127811,3570160948,128,355,5954.814048,4741.748776,1190.050606,606944,422468

In [ ]:
#Print the data frame information to look for missing data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OBJECTID       7 non-null      int64
 1   DISTRICT_NAME  7 non-null      object
 2   POP            7 non-null      int64
 3   Area           7 non-null      int64
 4   S_Yield_Ha     7 non-null      int64
 5   M_Yield_Ha     7 non-null      int64
 6   Crop_Area_Ha   7 non-null      float64
 7   S_Area_Ha      7 non-null      float64
 8   M_Area_Ha      7 non-null      float64
 9   S_Prod_Tot     7 non-null      int64
 10  M_Prod_Tot     7 non-null      int64
dtypes: float64(3), int64(7), object(1)
memory usage: 744.0+ bytes

In [ ]:
#Print to veiw the rows and colums for the second dataframe
df2.head()

,OBJECTID,SUBCOUNTY_NAME,DISTRICT_NAME,POP,Area,Karamoja,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,263,KACHERI,KOTIDO,17244,1067176155,Y,354.207411,1137.467019,7023.533691,6434.342449,528.124229,2.279092e+06,600723.892900
1,264,KOTIDO,KOTIDO,52771,597575188,Y,367.890523,1162.996687,13587.990760,12455.592640,824.767081,4.582294e+06,959201.382500
2,265,KOTIDO TOWN COUNCIL,KOTIDO,27389,23972401,Y,369.314177,1167.005832,1656.531855,1520.322052,8.561644,5.614765e+05,9991.488268
3,266,NAKAPERIMORU,KOTIDO,38775,419111591,Y,283.324569,852.366578,7087.823334,6761.488901,45.721712,1.915696e+06,38971.659080
4,267,PANYANGARA,KOTIDO,65704,880955930,Y,373.836926,1283.859882,10398.249390,10111.198130,172.611914,3.779939e+06,221609.511400

In [ ]:
#Check for missing data in the second dataframe by printing the dataframe info
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBJECTID        52 non-null     int64
 1   SUBCOUNTY_NAME  52 non-null     object
 2   DISTRICT_NAME   52 non-null     object
 3   POP             52 non-null     int64
 4   Area            52 non-null     int64
 5   Karamoja        52 non-null     object
 6   S_Yield_Ha      52 non-null     float64
 7   M_Yield_Ha      52 non-null     float64
 8   Crop_Area_Ha    52 non-null     float64
 9   S_Area_Ha       52 non-null     float64
 10  M_Area_Ha       52 non-null     float64
 11  S_Prod_Tot      52 non-null     float64
 12  M_Prod_Tot      52 non-null     float64
dtypes: float64(7), int64(3), object(3)
memory usage: 5.4+ KB

In [ ]:
#Print the colums of the second dataframe to look for related colums
df.columns

Index(['OBJECTID', 'DISTRICT_NAME', 'POP', 'Area', 'S_Yield_Ha', 'M_Yield_Ha',
       'Crop_Area_Ha', 'S_Area_Ha', 'M_Area_Ha', 'S_Prod_Tot', 'M_Prod_Tot'],
      dtype='object')

In [ ]:
#remane the Yiedls and area columns
df.rename(columns = {'POP':'DISTRICT_POP', 'Area':'DISTRICT_AREA', 'S_Yield_Ha':'S_DISTRICT_AREA', 'M_Yield_Ha':'M_Yield_Ha', })

In [ ]:
df2.columns

Index(['OBJECTID', 'SUBCOUNTY_NAME', 'DISTRICT_NAME', 'POP', 'Area',
       'Karamoja', 'S_Yield_Ha', 'M_Yield_Ha', 'Crop_Area_Ha', 'S_Area_Ha',
       'M_Area_Ha', 'S_Prod_Tot', 'M_Prod_Tot'],
      dtype='object')

**Column Naming**

The naming of the colums needs to be changed to have the district name in both files have a similar name and secondly to to differenciate the total yields for the districts and for the sub counties

In [ ]:
#rename district colum in df1 to match with ditrict name in dataframe 2
df.rename(columns={'NAME':'DISTRICT_NAME'}, inplace=True)
df.columns

Index(['OBJECTID', 'DISTRICT_NAME', 'POP', 'Area', 'S_Yield_Ha', 'M_Yield_Ha',
       'Crop_Area_Ha', 'S_Area_Ha', 'M_Area_Ha', 'S_Prod_Tot', 'M_Prod_Tot'],
      dtype='object')

In [ ]:
#export dataframe 1
df.to_csv('Uganda_Karamoja_District_Crop_Yield_Population_cleaned.csv', index = False)

In [ ]:
print(df.shape)

(7, 11)

**Conclusion**

From the analysis above, the data did not have any missing data and most of the data was significantly clean for analysis and visualization.
Visualization was dione useny Tableau.